"""fix cascade deletes and nullable assigned_to

Revision ID: 42c1a792ed02
Revises: 5243e0440e4a
Create Date: 2026-04-08 19:35:55.769389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42c1a792ed02'
down_revision: Union[str, Sequence[str], None] = '5243e0440e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('organization_members_org_id_fkey', 'organization_members', type_='foreignkey')
    op.create_foreign_key('organization_members_org_id_fkey', 'organization_members', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('tasks_assigned_to_fkey', 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'assigned_to', nullable=True)
    op.create_foreign_key('tasks_assigned_to_fkey', 'tasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_assigned_to_fkey', 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'assigned_to', nullable=False)
    op.create_foreign_key('tasks_assigned_to_fkey', 'tasks', 'users', ['assigned_to'], ['id'])

    op.drop_constraint('organization_members_org_id_fkey', 'organization_members', type_='foreignkey')
    op.create_foreign_key('organization_members_org_id_fkey', 'organization_members', 'organizations', ['org_id'], ['id'])

    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
