"""remove org_id from users

Revision ID: 5243e0440e4a
Revises: 8a40142e2f93
Create Date: 2026-04-07 15:15:51.691093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5243e0440e4a'
down_revision: Union[str, Sequence[str], None] = '8a40142e2f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_org_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_org_id_fkey'), 'users', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###
