"""added priority and due_date to tasks

Revision ID: 8a40142e2f93
Revises: 8b4ad9fb2052
Create Date: 2026-04-06 16:10:08.467827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a40142e2f93'
down_revision: Union[str, Sequence[str], None] = '8b4ad9fb2052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(), nullable='False', server_default='medium'))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable='True'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
