"""added slug and owner_id to organization

Revision ID: dfa31ce285cb
Revises: dff1ac192c92
Create Date: 2026-03-29 22:15:28.035129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfa31ce285cb'
down_revision: Union[str, Sequence[str], None] = 'dff1ac192c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_foreign_key(None, 'organizations', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_column('organizations', 'created_at')
    op.drop_column('organizations', 'owner_id')
    op.drop_column('organizations', 'slug')
    # ### end Alembic commands ###
