"""add refresh_tokens table

Revision ID: dff1ac192c92
Revises: 55b33e2f5764
Create Date: 2026-03-27 20:43:41.717462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff1ac192c92'
down_revision: Union[str, Sequence[str], None] = '55b33e2f5764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
        sa.Column('id', sa.Integer(),nullable=False),
        sa.Column('token', sa.String(),nullable=False),
        sa.Column('user_id', sa.Integer(),nullable=False),
        sa.Column('expires_at', sa.DateTime(),nullable=False),
        sa.Column('revoked', sa.Boolean(),nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'],['users.id'])
        )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###  


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
